namespace MFP.library.Enums
{
    public enum CommandTypes : uint
    {
        Segment = 0x1,
        Symbol_Table = 0x2,
        Symbol_Table_Gdb = 0x3,
        Thread = 0x4,
        Thread_Unix = 0x5,
        Lib_Load_VM = 0x6,
        Lib_VM_Id = 0x7,
        Identification_Info = 0x8,
        VM_File_Inclusion = 0x9,
        Pre_Page = 0xa,
        Dynamic_Symbol_Table = 0xb,
        Load_Dynamic_Library = 0xc,
        Id_Dynamic_Library = 0xc,
        Load_Dynamic_Linker = 0xd,
        Id_Dynamic_Linker = 0xf,
        Prebound_Dynamic_Library = 0x10,
        Routines = 0x11,
        Sub_Framework = 0x12,
        Sub_Umbrella = 0x13,
        Sub_Client = 0x14,
        Sub_Library = 0x15,
        TwoLevel_Hints = 0x16,
        Prebind_Checksum = 0x17,
        Load_Weak_Dynamic_Library = 0x18,
        Segment_64 = 0x19,
        Routines_64 = 0x1a,
        UUID = 0x1b,
        Runpath = 0x1c,
        Code_Signature = 0x1d,
        Segment_Split_Info = 0x1e,
        Re_Export_Dynamic_Library = 0x1f,
        Lazy_Load_Dynamic_Library = 0x20,
        Encryption_Info = 0x21,
        Dynamic_Library_Information = 0x22,
        Load_Upward_Dynamic_Library = 0x23,
        Version_Minimum_MacOSX = 0x24,
        Version_Minimum_IphoneOS = 0x25,
        Function_Starts = 0x26,
        Dynamic_Library_Environment = 0x27,
        Main = 0x28,
        Data_In_Code = 0x29,
        Source_Version = 0x2A,
        Dynamic_Library_Code_Signing = 0x2B,
        Encrpytion_Information_64 = 0x2C,
        Linker_Option = 0x2D
    }
}